### ISSUE TITLE
feature: datasource resource

### ISSUE THREAD

**Issue by andrewrynhard** [logicmonitor/terraform-provider-logicmonitor#1]
We should support the management of datasources via this TF provider. One use case is the updating of production datasources after writing and testing them in a testing environment. It is cumbersome to download the XML and upload. Additionally, this will allow teams to do peer reviews on datasources.

**Comment by woz5999** [comment]
I think this overlaps with the logicmodule registry and exchange. At the very least, this should be revisited once that is full production as i'm sure workflows will change
