### ISSUE TITLE
website auth block is required when require_auth = false

### ISSUE THREAD

**Issue by AntonSynchrofazatron** [logicmonitor/terraform-provider-logicmonitor#101]
Please fix issue when 
` require_auth = false`
this part is definitely a garbage... 
```
        auth = [{
          password = ""
          type = "basic"
          domain = ""
          user_name = ""
        }]
```
if it is removed, code is not able to be executed saying that auth block is required.... 
`Inappropriate value for attribute "steps": element 0: attribute "auth" is required.`
so i keep it and next when code is applied terraform plan always asks for changes like
```
~ auth                = [
                  + {
                      + domain    = ""
                      + password  = ""
                      + type      = "basic"
                      + user_name = ""
                    },
```

**Comment by lm-madhvi** [comment]
Closing this as this issue has been fixed.

**Comment by lm-madhvi** [comment]
Closing this as this issue has been fixed.
