### ISSUE TITLE
Data sources for single resource lookups should fail if multiple ids are returned for the specified filter

### ISSUE THREAD

**Issue by woz5999** [logicmonitor/terraform-provider-logicmonitor#11]
Currently, if the filter logicmonitor_device_group returns multiple ids, the data lookup succeeds, but subsequent references to logicmonitor_device_group.name.id fail with the error ```logicmonitor_device_group.pod_group: parent_id: cannot parse '' as int: strconv.ParseInt: parsing "5639,5640,3649": invalid syntax```

If the device group lookup is intended to return a single id, the lookup should throw an error. Otherwise, the issue doesn't manifest itself until you try to use the data source, which leads to confusing error messages and hides the actual source of the problem.

**Comment by pyang55** [comment]
this is addressed in the go sdk update and new tf provider v2
