### ISSUE TITLE
[Feature Request] Add website resource, to setup website monitoring from terraform

### ISSUE THREAD

**Issue by miked63017** [logicmonitor/terraform-provider-logicmonitor#21]
Hi,

It would be a nice feature to have if we could add website resources in terraform to setup website monitoring in LM.

Thanks!

**Comment by pyang55** [comment]
@miked63017 we are doing some updates to our go sdk and this should be coming soon. stay tuned!

**Comment by dsmith73** [comment]
Good afternoon - Any update on this?

**Comment by iehrenwaldDK** [comment]
Any updates, almost 2 years later?

**Comment by MaxAnderson95** [comment]
Any updates on this? Would really love to have this.

**Comment by lm-madhvi** [comment]
This feature has been added.
