### ISSUE TITLE
Provider review

### ISSUE THREAD

**Issue by catsby** [logicmonitor/terraform-provider-logicmonitor#3]
Hello! 

My name is Clint, I'm a member of the Terraform team @ HashiCorp.

I’ve taken a look at the provider here and would like to say great work so far! I do have feedback outlined below that I’d like to see addressed before we move on to the next steps. I’m opening this issues as a sort of checklist for tracking remaining items and discussion. The review was done on the git commit ee20159190a9e035db7240c2a8895a07e9b7544f .

- [x] README.md: Indicates there are two ways to set required arguments, but only shows Environment variables. Is there another way? For example, some providers allow you to provide a file path to a credentials file. 
- [x] Included Sirupsen/logrus library: While I’m personally a fan of this library, it should not be used in the context of Providers. Please use the log package that is a part of the Go standard library, so that the logs from this Provider match the format of other Providers
- [x] Resources/Data sources: please place the method defining the resource near the top of the file, as opposed to the bottom
- [x] Resource / Data source naming: Terraform style is to use underscores in-between key words, like `aws_ebs_snapshot`. Please try to match this style. Examples would be `resource_collectorgroup.go` should be `resource_collector_group.go`. Additionally, `logicmonitor_findcollectors` should be simply `logicmonitor_collectors`.
- [x] Several documentation sources contain a “Nested Filters” block which is malformed and not rendering correctly. 
- [x] Resource `logicmonitor_collectorgroup`: `description` is documented as required, but in the code it’s just optional
- [x] Resource `logicmonitor_collectorgroup`: On line 53 we log an error if the ID fails to parse, but we only log. If this were to error, the resulting ID value will be 0. This should be updated to return the error if this fails to parse. At best, the resource will behave oddly or error in another place, but at worse it could have destructive behavior. There are a few other places in the code base I observed this pattern. (https://github.com/logicmonitor/terraform-provider-logicmonitor/blob/ee20159190a9e035db7240c2a8895a07e9b7544f/logicmonitor/resource_collectorgroup.go#L53-L56)
- [x] Resource `logicmonitor_collectorgroup`: On line 93, if an error deleting occurs, an error is returned and the delete failes/stops. The `checkStatus` method used here returns an error if the response code is not “OK”. if the resource was already destroyed by other means, this will just sit in a failed state. Need to check the error here and if it’s 404 or similar, take that as “this resource has already been destroyed”, log that, and call d.SetId(“”). This seems to apply to all Resource delete methods (https://github.com/logicmonitor/terraform-provider-logicmonitor/blob/ee20159190a9e035db7240c2a8895a07e9b7544f/logicmonitor/resource_collectorgroup.go#L92-L95)

The latter few items are concrete demonstrations of some patterns I’ve seen and would like to be addressed before we move on. Please let me know if you have any questions!

Cheers,
Clint

-------
Update on 9/27/17

- [x] Resource `READ` methods need to update the local state with values returned from the API, to detect drift
- [x] Acceptance test failures: I'm getting the following failures:
```
$ make testacc TESTARGS="-run=TestAccLogicMonitor" 
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run=TestAccLogicMonitor -timeout 120m
?       github.com/logicmonitor/terraform-provider-logicmonitor [no test files]
=== RUN   TestAccLogicMonitorCollectorDataSource
--- FAIL: TestAccLogicMonitorCollectorDataSource (0.71s)
        testing.go:430: Step 0 error: Check failed: Check 1/2 error: Can't find logicmonitor collector data source: data.logicmonitor_findcollectors.collectors
=== RUN   TestAccLogicMonitorCollectorGroup
--- FAIL: TestAccLogicMonitorCollectorGroup (1.11s)
        testing.go:430: Step 0 error: Check failed: Check 2/3 error: Not found: logicmonitor_collectorgroup.group1
=== RUN   TestAccLogicMonitorDeviceGroup
--- FAIL: TestAccLogicMonitorDeviceGroup (1.15s)
        testing.go:430: Step 0 error: Check failed: Check 2/5 error: Not found: logicmonitor_devicegroup.group1
=== RUN   TestAccLogicMonitorDevices
--- PASS: TestAccLogicMonitorDevices (2.05s)
FAIL
FAIL    github.com/logicmonitor/terraform-provider-logicmonitor/logicmonitor    5.042s
make: *** [testacc] Error 1
```

**Comment by pyang55** [comment]
@catsby this is phenomenal feedback. Thank you so much! I will see if i can get most if not all addressed today

**Comment by pyang55** [comment]
hey @catsby can you shed a little more light on this comment

"Several documentation sources contain a “Nested Filters” block which is malformed and not rendering correctly."

**Comment by pyang55** [comment]
@catsby Hey Clint, i added all the changes to branch "hashicorp-changes". im going to create a PR, can you take a look and tell me if these fit the changes you had recommended. Thanks again for your work on this

**Comment by catsby** [comment]
Hey @pyang55 sorry for the delay, had a busy week last week 😉 

Regarding this:

```
"Several documentation sources contain a “Nested Filters” block which is malformed and not rendering correctly."
```

When I pulled the repository in and viewed what terraform.io would like like with your documentation pulled in, there was a block of markdown that wasn't rendering correctly. Specifically here:

- https://github.com/logicmonitor/terraform-provider-logicmonitor/blob/master/website/docs/d/findcollectors.html.markdown#nested-filters-blocks

`Nested filters blocks` appears to render fine there, but when I pulled it locally, the bullets were all in-line. I believe all you need is a newline before the bullets begin, just how `Argument Reference` is done. 

Great to see the changes! I'll take another pass here

**Comment by catsby** [comment]
The changes look good! The next step for me is quickly verifying the credentials we've been given and verifying some of the tests. I believe next we'll then need to work on transferring to the [Terraform Providers](http://github.com/terraform-providers) org. 

Thanks for the fast turn around!

**Comment by pyang55** [comment]
@catsby sorry about that, the https://github.com/logicmonitor/terraform-provider-logicmonitor/blob/master/website/docs/d/findcollectors.html.markdown#nested-filters-blocks was a markdown we forgot to delete when we committed the renamed markedowns. this has been fixed

**Comment by catsby** [comment]
Hello – I'm trying to test this out using the sample config from the docs:

- https://github.com/logicmonitor/terraform-provider-logicmonitor/blob/master/website/docs/r/device.html.markdown

The first error I get is this:

```
1 error(s) occurred:

* module root: 1 error(s) occurred:

* resource 'logicmonitor_device.host' config: unknown resource 'logicmonitor_device_group.devicegroups' referenced in variable logicmonitor_device_group.devicegroups.id
```

`hostgroup_id` needs to be changed to this:

    hostgroup_id = "${data.logicmonitor_device_group.devicegroups.id}"

After fixing that, the next error I get is this:

```
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.logicmonitor_device_group.devicegroups: Refreshing state...
data.logicmonitor_collectors.collectors: Refreshing state...
Error refreshing state: 1 error(s) occurred:

* data.logicmonitor_device_group.devicegroups: 1 error(s) occurred:

* data.logicmonitor_device_group.devicegroups: data.logicmonitor_device_group.devicegroups: Found no device groups with filter name~Mesos
```

That one I'm not sure what to make of, though things appear to work from a Terraform standpoint, I'm not sure if theres an error in the code or my usage that leads to that not being found. 

Is there other setup I'm missing here?

**Comment by catsby** [comment]
Additionally: I did just notice that the `READ` methods for all the included resources seem to only verify that the resource exits, and do not actually update the local state with values returned from the API. This makes detecting drift impossible. For example, I created a test device successfully via terraform, and then modified it in the web console. After doing so, Terraform did not report and diff, even though the configuration and actual state of the device no longer matched. The `READ` methods need to update the values of the schema.

**Comment by pyang55** [comment]
hey @catsby, fixed the read method issue. As for the testing, that was unfortunately because i copied/pasted an existing main.tf from testing. It was looking for a host group that did not exist. I have fixed all these issues. please let me know if there are additional issues

**Comment by catsby** [comment]
Hey @pyang55 , things look good now! I'm going to close this issue and we'll start with the next step in the process 👍
