### ISSUE TITLE
Alert Rules and Escalation Chains

### ISSUE THREAD

**Issue by iehrenwaldDK** [logicmonitor/terraform-provider-logicmonitor#35]
I would love to be able to define Alert Rules and Escalation Chains within Terraform.

**Comment by lm-madhvi** [comment]
This functionality added , now alert rules and escalation chains can be defined  by LogicMonitor terraform provider .

**Comment by lm-madhvi** [comment]
This functionality added , now alert rules and escalation chains can be defined by LogicMonitor terraform provider .
