### ISSUE TITLE
Publish 2.0.0 to the Terraform Registry

### ISSUE THREAD

**Issue by cdiehl-prot** [logicmonitor/terraform-provider-logicmonitor#36]
Curious why it has not been published to hashicorp's official registry and no updates in years?
https://registry.terraform.io/providers/logicmonitor/logicmonitor/1.3.4
I noticed that the 2.0.0 release requires manually building the provider and the docs to be viewed in the code itself here on GitHub.

I intend to use Terraform Cloud and I suppose we can use it via our private registry and whatnot, but it is not our intellectual property, seems odd to have a secondary mirror hosting it when it makes most sense for the Logic Monitor team to upload it to the official registry.

I see there was a LOT of good functionality added to the 2.0.0 release and would love to see an official release on the TF Registry. I have been able to use much of the added resources and data sources with 2.0.0 and have had success adding a Device Group, an AWS Account via Device Group, getting the AWS external ID for the role using the data source, creating a collector group, creating a collector, etc. 
It has all been highly usable to me.  Once I found the docs hidden in the code that is.

**Comment by gagansingh355** [comment]
Fixed by this https://github.com/logicmonitor/terraform-provider-logicmonitor/pull/37. Closing this issue.

**Comment by iehrenwaldDK** [comment]
Documentation is absent from https://registry.terraform.io/providers/logicmonitor/logicmonitor/2.0.0 - will this get pushed too?

**Comment by kabeladev** [comment]
SHA256 checksum also seem to be wrong 

│ Error: Failed to install provider
│
│ Error while installing logicmonitor/logicmonitor v2.0.0: checksum list has unexpected SHA-256 hash fdd4c4958754514e99e8b58ed55a9af354099343bc96d10da333f27428343743 (expected
│ b2084adf8fd549b4ea3b618e0b6ccb5cf5f45e33d50dd6d7e9aa610fef4d9d96)

**Comment by kabeladev** [comment]
both documentation and SHA issues sorted with v2.0.1
