### ISSUE TITLE
Terraform execution on CloudDevice Group

### ISSUE THREAD

**Issue by manusabu11** [logicmonitor/terraform-provider-logicmonitor#49]
The execution with cloud device group isn't idempotent as each time external id is changing.
The first run on code was successful but the consecutive will fail with the error
++++++++++++++
 Error: unexpected: [PUT /device/groups/{id}][403] updateDeviceGroupById default  &{ErrorCode:1403 ErrorDetail:<nil> ErrorMessage:The specified role is invalid. Please confirm that the role references the correct account and external IDs.}
++++++++++++
Any suggestion on how to overcome this? 

https://registry.terraform.io/providers/logicmonitor/logicmonitor/latest/docs/resources/device_group_html

In addition to the above, here the wait time will work on Linux and won't on windows. So in my suggestion, it is better to include time_sleep instead of null_resource

**Comment by manusabu11** [comment]
Okay, including lifecycle management for now as it is really annoying

**Comment by manusabu11** [comment]
Would like to know if any other workaround or solution is available.

**Comment by lm-madhvi** [comment]
Please make sure you are using the correct role "TF-Integration-Role" . Are you still facing this issue?
