### ISSUE TITLE
Add delete permanently feature

### ISSUE THREAD

**Issue by rtsai123** [logicmonitor/terraform-provider-logicmonitor#6]
I just started using Terraform Logic Monitor provider. I noticed on the destroy that the devices get moved to delete bucket in Logic Monitor but I have to permanently delete the device. It would be nice to have a flag that will do the permanent delete on destroy.

resource "logicmonitor_device" "host" {
  ip_addr = "host"
  disable_alerting = false
  collector = "${data.logicmonitor_collectors.collectors.id}"
  hostgroup_id = "${data.logicmonitor_device_group.devicegroup.id}"
  **permanently_delete = true #or something similar**
}

**Comment by pyang55** [comment]
@rtsai123 we are aware of this issue and will be issuing a fix. This will not affect the provider in any way but a change on the logicmonitor side. Sorry for the confusion. Please feel free to address with any more questions

**Comment by rtsai123** [comment]
@pyang55 - wow thats for the quick response! Just curious any idea when it will be fixed. Again no rush on my side.

**Comment by pyang55** [comment]
@rtsai123 the issue we will be addressing is with the "recently delete" functionality. This should be fixed soon. There will be a feature in the future where you can have the option of keeping the deleted resource in the recycled bucket

**Comment by katbyte** [comment]
@pyang55,

Just wondering if this has now been fixed?

**Comment by pyang55** [comment]
@katbyte we patched this issue where all api calls made by the provider will default to delete the device permanently in LM. We will be adding a flag later on if the user wishes to add the deleted device to recycle bin

**Comment by pyang55** [comment]
I am closing the issue for now as we have addressed the immediate issue, new updates with the provider will be coming soon with our new APIV2 GO SDK
