### ISSUE TITLE
Add Role resource to provider

### ISSUE THREAD

**Issue by Shocktrooper** [logicmonitor/terraform-provider-logicmonitor#69]
We would like to auto create roles and permissions for those roles for our development teams with our automation and link them with SAML roles.  Unfortunately there is no role resource in the terraform provider so this currently would have to be done manually.  It would be appreciated for this resource to be added along with any accompanying resource needed to manage role privileges with the terraform provider for a role.

References:
- https://www.logicmonitor.com/support/settings/users-and-roles/roles#
- https://www.logicmonitor.com/support/adding-roles

**Comment by lm-madhvi** [comment]
With the exitsting logicmonitor provider  we cannot manage  roles and permissions. We need to look into the feasibility of managing roles and permissions into LM using Terraform .

**Comment by Shocktrooper** [comment]
No worries my company went with datadog partially because we could manage service accounts and teams via terraform.  Just wanted to mention that other platforms have this capability via terraform already.
