### ISSUE TITLE
logicmonitor_website does not support params such as 'path', 'auth' etc.

### ISSUE THREAD

**Issue by Dmitriymdn85** [logicmonitor/terraform-provider-logicmonitor#72]
logicmonitor_website does not support params such as `path`, `auth`, etc.
Also need some more explanation if it's possible to do POST request with key=value params

**Comment by Dmitriymdn85** [comment]
in addition there is some minor typos in readme datasources.
https://github.com/logicmonitor/terraform-provider-logicmonitor/blob/master/website/docs/d/website_html.markdown
`data "logicmonitor_Website"` -> `data "logicmonitor_website"`
https://github.com/logicmonitor/terraform-provider-logicmonitor/blob/master/website/docs/d/website_group_html.markdown
`data "logicmonitor_WebsiteGroup"` -> data `"logicmonitor_website_group"`

**Comment by lm-madhvi** [comment]
with the new provider release we have added these params path , auth etc. for logicmonitor_website.
