### ISSUE TITLE
Data Sources documentation wrong?

### ISSUE THREAD

**Issue by Scholdan** [logicmonitor/terraform-provider-logicmonitor#73]
I'm trying to get my collector group and collector ID

But it seems that the examples you provide are not working?
Also the comment seems a little wrong for a datasource

```
# create a new LogicMonitor collector group
data "logicmonitor_CollectorGroup" "my_CollectorGroup" {
        filter = "description~\"Group for collectors dedicated to testing purpose\""
        depends_on = [
            logicmonitor_collector_group.my_collector_group
        ]
}
```

```
# create a new LogicMonitor collector
data "logicmonitor_Collector" "my_Collector" {
        filter = "description~\"Linux Collector\""
        depends_on = [
            logicmonitor_collector.my_collector
        ]
}
```

**Comment by lm-madhvi** [comment]
To get  the collector id  and collector group id  you have to set it like 
value   = data.logicmonitor_collector.my_collector.id
value       = data.logicmonitor_collector_group.my_collector_group.id

Please check these examples:

data "logicmonitor_collector" "my_collector" {
    filter = "description~\"Linux Collector\""
 	depends_on = [
		logicmonitor_collector.my_collector
 	]
}

output "collector" {
  description = "collector"
  value       = data.logicmonitor_collector.my_collector.id
}

data "logicmonitor_collector_group" "my_collector_group" {
     filter = "description~\"Group for collectors dedicated to testing purpose\""
	depends_on = [
 		logicmonitor_collector_group.my_collector_group
	]
}

output "collector_group" {
   description = "collector group list"
   value       = data.logicmonitor_collector_group.my_collector_group.id
}

If you are still facing any error , please let us know the exact error message .
Also we have updated the comment for the datasource in the latest release.
