### ISSUE TITLE
logicmonitor_dashboard_group using widget_tokens

### ISSUE THREAD

**Issue by wellingk** [logicmonitor/terraform-provider-logicmonitor#74]
### Issue ###
i've imported a dashboard group and I am struggling with `widget_tokens`.

`inherit_list = []` appears to be required as an element of `widget_tokens` and yet when i try to include it I receive the error.

```
Error: Computed attributes cannot be set
│ 
│   with logicmonitor_dashboard_group.aws-custom-billing-dashboard_group,
│   on dashboard-aws-custom-dashboard.tf line 1, in resource "logicmonitor_dashboard_group" "custom-dashboard-group":
│    1: resource "logicmonitor_dashboard_group" "aws-custom-billing-dashboard_group" {
│ 
│ Computed attributes cannot be set, but a value was set for "widget_tokens.1.type".
```

The documentation is not really very helpful in that it only states 

> [inherit_list](https://registry.terraform.io/providers/logicmonitor/logicmonitor/latest/docs/resources/dashboard_group_html#inherit_list) (required) - Need to pass 'null' value

I've tried every which way to pass a null value to this as suggested and am getting nowhere.

### Expected Resolution ###
* Please can the documentation be updated with the correct usage
* If this is not working please can the issue with it be resolved as some dashboards are complicated to create and there is no point in doing stuff half in code!

Thanks

**Comment by lm-madhvi** [comment]
As inherit_list and type are computed attribute (i.e. readonly), it cannot be configured, so we need to pass null value in it .
widget_tokens =[
  {
    name = "string"
    type = null
    inherit_list = null 
    value = "string"
  }]
