### ISSUE TITLE
logicmonitor_website - Setting the Relative URL Path

### ISSUE THREAD

**Issue by wellingk** [logicmonitor/terraform-provider-logicmonitor#75]
###Issue###

i've imported a website that was manually created in LM before I decided to start using Terraform

My website has a couple of `steps = []` in it one of which I need to be able to set the Relative URL path with a value.

The [documentation](https://registry.terraform.io/providers/logicmonitor/logicmonitor/latest/docs/resources/website_html) does not suggest that this may be added. 

Can it be?

###Expected Resolution###
* Understand how I am able to add a relative URL Path to my step

Thanks

**Comment by lm-madhvi** [comment]
With the new  provider release  , you can set URL for the steps. Please check the updated [documentation ](https://registry.terraform.io/providers/logicmonitor/logicmonitor/latest/docs/resources/website)
