### ISSUE TITLE
Using the Template Argument

### ISSUE THREAD

**Issue by wellingk** [logicmonitor/terraform-provider-logicmonitor#76]
I have been trying to import a dashboard into Terraform using the Logic Monitor Terraform Provider.

I have exported the json template for the dashboard from the LogicMonitor Console and want to include that using the "template" argument.Which I guess is what we are supposed to do.

The Documentation for the LogicMonitor Terraform Provider is not very helpful.

Please can you tell me the correct Syntax to use to include the template?

Currently I am using:

`template = file("${path.module}/templates/AWS_Custom_Billing_Dashboard_Using_Tag_Values.json")`

to point at a file in the templates folder, and the output that I am receiving is: -

```
╷
│ Error: Incorrect attribute value type
│ 
│ on dashboard-aws-custom-billing-dashboards.tf line 30, in resource "logicmonitor_dashboard" "aws-billing-with-tag-values-dashboard":
│ 30: template = file("${path.module}/templates/AWS_Custom_Billing_Dashboard_Using_Tag_Values.json")
│ ├────────────────
│ │ path.module is "."
│ 
│ Inappropriate value for attribute "template": map of string required.
╵
```
Thanks for any assistance.

Kate

[https://registry.terraform.io/providers/logicmonitor/logicmonitor/latest/docs/resources/dashboard_html](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fregistry.terraform.io%2Fproviders%2Flogicmonitor%2Flogicmonitor%2Flatest%2Fdocs%2Fresources%2Fdashboard_html&data=05%7C01%7Ck.welling%40wellcome.org%7Cffc993318c0d4c32d84708dbf00cf871%7C3b7a675a1fc84983a100cc52b7647737%7C0%7C0%7C638367710744462340%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ZMACcKQGgd%2FGxkE%2BBP%2FOGO4EacYItVsCLsvPgRNnuK8%3D&reserved=0)

**Comment by sivashankar-tomtom** [comment]
I am also getting the same issue. I am using the logicmonitor version 2.0.17. Is this issue resolved?
