### ISSUE TITLE
Reduce unnecessary execution plan actions

### ISSUE THREAD

**Issue by clarkm5** [logicmonitor/terraform-provider-logicmonitor#8]
If a secure property is set then we see actions such as this every time we plan/apply:

  ~ logicmonitor_device_group.group_name
      properties.jmx.pass:             "********" => "p@ssw0rd"

If a device inherits properties from a group then we see the following every time we plan/apply:

  ~ module.module_name.logicmonitor_device.host[0]
      properties.%:                    "3" => "2"
      properties.snmp.version:         "v2c" => ""
      properties.system.categories:    "snmpTCPUDP,Netsnmp,snmpHR,snmp" => ""

In even a relatively small terraform project, these swap the output, making it very difficult to see what is going on in the execution plan.

**Comment by pyang55** [comment]
@clarkm5 I think this might be a limitation of our apiv1, apiv2 will be out soon and this should be fixed along with many new features (dashboard upload/creation, services automation etc). I appreciate you using the provider and providing great feedback!

**Comment by clarkm5** [comment]
@pyang55 thanks for the quick responses - the logicmonitor provider is a great addition to our IaC projects!  I look forward to seeing what else changes in the new API
