### ISSUE TITLE
logicmonitor_website missing support for testlocations

### ISSUE THREAD

**Issue by cnagamor** [logicmonitor/terraform-provider-logicmonitor#80]
In the `logicmonitor_website` resource docs, there's a mention of `testLocations`, but there's no argument to configure this. 

```
* `use_default_location_setting` - true: The checkpoint locations configured in the website Default Settings will be used
false: The checkpoint locations specified in the testLocation will be used
```

This is required for internal websites that can't use the internal default locations.

**Comment by lm-madhvi** [comment]
TestLocation has been added and will be available in the next release.
