### ISSUE TITLE
logicmonitor_website steps use_default_root does not work

### ISSUE THREAD

**Issue by matzter** [logicmonitor/terraform-provider-logicmonitor#81]
Whenever I try to deploy my step with the flag "use_default_root" false and an URL the terraform provider will accept it, but save the state with "true" and logic monitor will have a step that uses the default root domain.

Example

`resource "logicmonitor_website" "test" {
  type                         = "webcheck"
  name                         = "test check"
  domain                       = "www.logicmonitor.com"
  polling_interval             = 5
  disable_alerting             = true
  group_id                     = 105
  transition                   = 1
  user_permission              = "write"
  individual_alert_level       = "warn"
  overall_alert_level          = "warn"

  steps = [
    {
      schema              = "https"
      resp_type           = "config"
      timeout             = 30
      match_type          = "plain"
      description         = "string"
      use_default_root    = true
      http_method         = "GET"
      enable              = true
      http_version        = "1.1"
      http_headers        = "X-Version:3"
      follow_redirection  = true
      post_data_edit_type = ""
      name                = "__step0"
      req_type            = "config"
      fullpage_load       = false
      require_auth        = false
      path                = "string"
      auth = [{
        password  = "string"
        type      = "basic"
        domain    = "string"
        user_name = "string"
      }]
      keyword      = ""
      http_body    = ""
      resp_script  = ""
      req_script   = "string"
      label        = "string"
      url          = "/"
      type         = "config"
      invert_match = false
      status_code  = "200"
    },
    {
      name             = "__step1"
      url              = "google.com"
      description      = ""
      use_default_root = false
      enable           = true
      follow_redirection = true
      fullpage_load    = false
      http_body        = ""
      http_headers     = ""
      http_method      = "GET"
      http_version     = "1.1"
      invert_match     = false
      keyword          = ""
      label            = ""
      match_type       = "plain"
      path             = ""
      post_data_edit_type = ""
      req_script       = ""
      req_type         = "config"
      require_auth     = false
      resp_script      = ""
      resp_type        = "config"
      schema           = "https"
      status_code      = ""
      timeout          = 30
      type             = "config"
        auth = [{
        password  = "string"
        type      = "basic"
        domain    = "string"
        user_name = "string"
      }]
    }
  ]
}`

**Comment by AntonSynchrofazatron** [comment]
same.. really appreciate if this can be fixed. this feature works from LM UI. but not from TF code

**Comment by lm-madhvi** [comment]
This issue has been fixed in the provider version v2.0.17.
