### ISSUE TITLE
Escsalation Chains resource only allows 1 destination per stage

### ISSUE THREAD

**Issue by ghost** [logicmonitor/terraform-provider-logicmonitor#83]
Trying to add more than 1 destination per stage will result in the logicmonitor provider separating the destinations into separate stages.

**Comment by lm-madhvi** [comment]
When you want to create time based chain , you need to add subchain which is destinations field, you can add more than one destinations(i.e. subchains) and more than one stage  in a subchain.

**Comment by ghost** [comment]
I never mentioned a time based chain at all? 

To be clear, I'm trying to create the most basic escalation chain, simply with 2 destinations on a single stage. 

I can do this via the UI, and when I import that into code, it specifies the following configuration but if you then apply this exact configuration after an import, it will create a chain with two stages. 

`      stages = [
        {
          addr    = "ServiceNow"
          type    = "ADMIN"
          method  = "ServiceNow DEV Integration"
          contact = ""
        },
        {
          addr    = "xxxxx"
          type    = "ARBITRARY"
          method  = "email"
          contact = ""
        },
`

**Comment by lm-madhvi** [comment]
Hi @ChrisCAG , 

Thanks for identifying this issue , we started working on this fix.

**Comment by lm-madhvi** [comment]
Hi @ChrisCAG ,

We have addressed and resolved the mentioned issue, subsequently incorporating the necessary fixes into the latest release (version 2.0.15).

Thanks
