### ISSUE TITLE
logicmonitor_website: no way to add SSL expiration check via tf

### ISSUE THREAD

**Issue by AntonSynchrofazatron** [logicmonitor/terraform-provider-logicmonitor#84]
In LM UI it is possible to set 
Alert on SSL Errors
 Halt on SSL errors
 Alert on Certificate Expiration

But i don't see that in tf provider. Was this missed during development?
That would be nice to have 
```
  triggersslexpirationalert = true / false 
  triggersslstatusalert = true /false
  alertexpr  = "< 30 15"
```
![image](https://github.com/logicmonitor/terraform-provider-logicmonitor/assets/167319334/293217a6-9779-4e9f-9f2e-cd90a99fa5d7)

**Comment by lm-madhvi** [comment]
Hi @AntonSynchrofazatron , 

Thanks for raising this issue , we will add these fields in tf provider also .

**Comment by lm-madhvi** [comment]
Hi @AntonSynchrofazatron ,

We have introduced additional fields to facilitate SSL expiration checks. These enhancements integrated into our Terraform provider, will be available with the next release.

Thanks
