### ISSUE TITLE
logicmonitor_datasource example errors

### ISSUE THREAD

**Issue by ghost** [logicmonitor/terraform-provider-logicmonitor#87]
Replication steps

1. Open your repo and copy in the example .tf code listed.

2. Try to run a plan.

Line 3 is showing a syntax error
`  applies_to = "system.deviceId == \"22\"` 
you're missing a closing quote.

Fixing that results in
Too few blocks specified for "collector_attribute": At least 1 block(s) are expected for "collector_attribute"

![image](https://github.com/logicmonitor/terraform-provider-logicmonitor/assets/157688578/d7350af3-8e8e-4f6a-8e77-91f669449c9b)

**Comment by ghost** [comment]
This can be mitigated by turning off advanced validation in vs code's settings, but figured it best to log the issue as by default this is going to cause confusion.

**Comment by lm-madhvi** [comment]
This issue is fixed and will be available by the next release.
