### ISSUE TITLE
logicmonitor_datasources -- raw_data_field_name doesnt apply

### ISSUE THREAD

**Issue by ghost** [logicmonitor/terraform-provider-logicmonitor#89]
When trying to apply a datasource with the following datapoint 

`  data_points = [
     {
      alert_body                      = ""
      alert_expr                      = ""
      alert_expr_note                 = ""
      alert_subject                   = ""
      max_value                       = null
      min_value                       = null
      alert_clear_transition_interval = 0
      alert_for_no_data               = 1
      alert_transition_interval       = 5
      data_type                       = 7
      description                     = <<-EOT
                    Error severity level

                    Status Code:
                    Unknown = 0
                    Normal = 1
                    Ignore = 2
                    Severe = 3
                    Critical = 4
                EOT
      max_digits                      = 4
      name                            = "ErrorControl"
      post_processor_method           = "json"
      post_processor_param            = "ErrorControl"
      raw_data_field_name             = "output"
      type                            = 2
     },`
     
    The provider shows an output as the following

`      ~ data_points            = [
          ~ {
                name                            = "ErrorControl"
              + raw_data_field_name             = "output"
                # (15 unchanged attributes hidden)
            },`

however when you apply this change via terraform, the lm datasource is not updated, further plans/applies show the same output

**Comment by lm-madhvi** [comment]
Hi @ChrisCAG  , Thanks for raising this issue. We've replicated the problem on our end and will investigate and resolve it.
