### ISSUE TITLE
logicmonitor_datasource ActiveDiscovery Missing Attributes & errors when applying.

### ISSUE THREAD

**Issue by ghost** [logicmonitor/terraform-provider-logicmonitor#90]
[enable_auto_discovery](https://registry.terraform.io/providers/logicmonitor/logicmonitor/latest/docs/resources/datasource#enable_auto_discovery) - Enable Auto Discovery or not when this data source has multi instance: false|true

When using this, there's no option to provide additional configuration, such as:
- automatically delete instances
- discovery schedule
- discovery method
- parameters
- extracting ILP's
- filters

This causes the request to fail if active discovery is enabled.

![image](https://github.com/logicmonitor/terraform-provider-logicmonitor/assets/157688578/0d608c2b-9414-469f-b5e8-5b5ad106290d)

**Comment by lm-madhvi** [comment]
Hi @ChrisCAG ,

We will add these attributes for  logicmonitor_datasource .

Thanks

**Comment by lm-madhvi** [comment]
These attributes added and released with provider version v2.0.17
